// Lista dos bancos mais usados no Brasil (código COMPE/Febraban + nome) —
// dado público estável, usado só pra sugerir na hora de cadastrar uma conta
// bancária (não precisa ser exaustiva dos ~400 códigos existentes, só
// cobrir os bancos que um cliente da SOMA realistamente usaria).
export const BANCOS_BRASIL: { codigo: string; nome: string }[] = [
  { codigo: "001", nome: "Banco do Brasil" },
  { codigo: "003", nome: "Banco da Amazônia" },
  { codigo: "004", nome: "Banco do Nordeste" },
  { codigo: "021", nome: "Banestes" },
  { codigo: "025", nome: "Banco Alfa" },
  { codigo: "033", nome: "Santander" },
  { codigo: "037", nome: "Banpará" },
  { codigo: "041", nome: "Banrisul" },
  { codigo: "047", nome: "Banese" },
  { codigo: "070", nome: "BRB — Banco de Brasília" },
  { codigo: "077", nome: "Banco Inter" },
  { codigo: "084", nome: "Uniprime" },
  { codigo: "085", nome: "Ailos (Cooperativa)" },
  { codigo: "089", nome: "Cooperativa Sicredi" },
  { codigo: "104", nome: "Caixa Econômica Federal" },
  { codigo: "121", nome: "Banco Agibank" },
  { codigo: "136", nome: "Unicred" },
  { codigo: "197", nome: "Stone" },
  { codigo: "208", nome: "Banco BTG Pactual" },
  { codigo: "212", nome: "Banco Original" },
  { codigo: "218", nome: "Banco BS2" },
  { codigo: "224", nome: "Banco Fibra" },
  { codigo: "237", nome: "Bradesco" },
  { codigo: "246", nome: "Banco ABC Brasil" },
  { codigo: "260", nome: "Nu Pagamentos (Nubank)" },
  { codigo: "265", nome: "Banco Fator" },
  { codigo: "290", nome: "PagSeguro (PagBank)" },
  { codigo: "318", nome: "Banco BMG" },
  { codigo: "320", nome: "Banco Industrial e Comercial (China Construction)" },
  { codigo: "323", nome: "Mercado Pago" },
  { codigo: "336", nome: "Banco C6" },
  { codigo: "341", nome: "Itaú Unibanco" },
  { codigo: "348", nome: "Banco XP" },
  { codigo: "356", nome: "Banco Real (Santander)" },
  { codigo: "366", nome: "Banco Société Générale Brasil" },
  { codigo: "380", nome: "PicPay" },
  { codigo: "389", nome: "Banco Mercantil do Brasil" },
  { codigo: "399", nome: "HSBC Bank Brasil" },
  { codigo: "422", nome: "Banco Safra" },
  { codigo: "453", nome: "Banco Rural" },
  { codigo: "456", nome: "Banco MUFG Brasil" },
  { codigo: "464", nome: "Banco Sumitomo Mitsui Brasileiro" },
  { codigo: "473", nome: "Banco Caixa Geral - Brasil" },
  { codigo: "477", nome: "Citibank" },
  { codigo: "479", nome: "Banco ItaúBank (antigo Bank of America)" },
  { codigo: "487", nome: "Deutsche Bank" },
  { codigo: "488", nome: "JPMorgan Chase Bank" },
  { codigo: "492", nome: "ING Bank" },
  { codigo: "505", nome: "Banco Credit Suisse" },
  { codigo: "545", nome: "Senso Corretora" },
  { codigo: "600", nome: "Banco Luso Brasileiro" },
  { codigo: "604", nome: "Banco Industrial do Brasil" },
  { codigo: "610", nome: "Banco VR" },
  { codigo: "611", nome: "Banco Paulista" },
  { codigo: "612", nome: "Banco Guanabara" },
  { codigo: "613", nome: "Omni Banco" },
  { codigo: "623", nome: "Banco PAN" },
  { codigo: "633", nome: "Banco Rendimento" },
  { codigo: "634", nome: "Banco Triângulo" },
  { codigo: "637", nome: "Banco Sofisa" },
  { codigo: "652", nome: "Itaú Unibanco Holding" },
  { codigo: "653", nome: "Banco Indusval" },
  { codigo: "654", nome: "Banco Digimais" },
  { codigo: "655", nome: "Banco Votorantim (BV)" },
  { codigo: "707", nome: "Banco Daycoval" },
  { codigo: "735", nome: "Banco Neon" },
  { codigo: "739", nome: "Banco Cetelem" },
  { codigo: "741", nome: "Banco Ribeirão Preto" },
  { codigo: "743", nome: "Banco Semear" },
  { codigo: "745", nome: "Banco Citibank (Corporate)" },
  { codigo: "746", nome: "Banco Modal" },
  { codigo: "747", nome: "Banco Rabobank" },
  { codigo: "748", nome: "Sicredi" },
  { codigo: "751", nome: "Scotiabank Brasil" },
  { codigo: "752", nome: "Banco BNP Paribas Brasil" },
  { codigo: "755", nome: "Bank of America Merrill Lynch" },
  { codigo: "756", nome: "Banco Sicoob" },
  { codigo: "757", nome: "Banco Keb Hana do Brasil" },
];
